# Generated by Django 3.0.2 on 2020-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchr',
            name='site',
            field=models.IntegerField(default=None, null=True, verbose_name='Участок'),
        ),
    ]
