# Generated by Django 3.0.2 on 2020-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0002_paymentchr_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='N участка')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='account_info',
            field=models.CharField(max_length=100, null=True, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='bank_acc',
            field=models.CharField(max_length=100, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='doc_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='s_amount',
            field=models.CharField(max_length=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='s_pay_date',
            field=models.CharField(max_length=10, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='type_op',
            field=models.CharField(max_length=2, null=True, verbose_name='Вид операции'),
        ),
    ]
