# Generated by Django 3.0.2 on 2020-02-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0003_auto_20200210_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchr',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bakovka4.Land', verbose_name='Участок'),
        ),
    ]
