# Generated by Django 3.0.2 on 2020-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0004_auto_20200210_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchr',
            name='purpose',
            field=models.CharField(choices=[('electrycity', 'электричество'), ('road', 'дороги'), ('membership', 'членские взносы'), ('common light', 'общий свет'), ('common water', 'общий водопровод'), ('common cadaster', 'общий кадастр'), ('water', 'вода'), ('truc', 'грузовой транспорт')], max_length=50, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='pay_purpose',
            field=models.CharField(max_length=300, verbose_name='Описание платежа'),
        ),
    ]
