# Generated by Django 3.0.2 on 2020-02-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0006_auto_20200223_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchr',
            name='parent_paym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bakovka4.PaymentChr', verbose_name='Из платежа'),
        ),
    ]
