# Generated by Django 3.0.2 on 2020-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0007_paymentchr_parent_paym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentchr',
            old_name='parent_paym',
            new_name='parent_pay_id',
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='account_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='bank_acc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='doc_num',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='purpose',
            field=models.CharField(blank=True, choices=[('membership', 'членские взносы'), ('electrycity', 'электричество'), ('water', 'вода'), ('road', 'дороги'), ('truc', 'грузовой транспорт'), ('common_cadaster', 'общий кадастр'), ('common_water', 'общий водопровод'), ('common_light', 'общий свет')], default='', max_length=50, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='s_amount',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='s_pay_date',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='type_op',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Вид операции'),
        ),
    ]
