# Generated by Django 3.0.2 on 2020-03-05 16:34

import bakovka4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0008_auto_20200223_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='memb_from',
            field=models.CharField(default='06.2014', max_length=7, validators=[bakovka4.models.validate_month], verbose_name='Взносы с месяца'),
        ),
        migrations.AddField(
            model_name='land',
            name='memb_to',
            field=models.CharField(default='03.2020', max_length=7, validators=[bakovka4.models.validate_month], verbose_name='Взносы по месяц'),
        ),
        migrations.AlterField(
            model_name='paymentchr',
            name='purpose',
            field=models.CharField(blank=True, choices=[('membership', 'Членские взносы'), ('electrycity', 'Электричество'), ('water', 'Вода'), ('road', 'Дороги'), ('truc', 'Грузовой транспорт'), ('common_cadaster', 'Общий кадастр'), ('common_water', 'Общий водопровод'), ('common_light', 'Общий свет')], default='', max_length=50, verbose_name='Назначение'),
        ),
    ]
