# Generated by Django 3.0.2 on 2020-05-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0010_auto_20200309_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер счетчика')),
                ('type', models.CharField(blank=True, choices=[('electrycity', 'Электричество'), ('water', 'Вода')], default='', max_length=50, verbose_name='Тип счетчика')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bakovka4.Land', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indic_date', models.DateField(verbose_name='Дата показания')),
                ('indic_value', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Показание')),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bakovka4.Meter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
            },
        ),
    ]
