# Generated by Django 3.0.2 on 2020-05-11 06:37

import bakovka4.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakovka4', '0011_indication_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020', max_length=4, validators=[bakovka4.models.validate_year], verbose_name='Год')),
                ('count', models.IntegerField(default=0, verbose_name='Количество машин')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bakovka4.Land', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
